#!/bin/bash

if [ ! -e "/usr/local/hestia/data/users/admin" ]; then
    exit
fi

###############################################################
#                Initialize functions/variables               #
###############################################################

# Load upgrade functions and variables
source /usr/local/hestia/conf/hestia.conf
source /usr/local/hestia/install/upgrade/upgrade.conf
source /usr/local/hestia/func/main.sh
source /usr/local/hestia/func/upgrade.sh

###############################################################
#             Set new version numbers for packages            #
###############################################################
# Hestia Control Panel
new_version=$(dpkg -l | awk '$2=="hestia" { print $3 }')

###############################################################
#               Begin standard upgrade routines               #
###############################################################

# Set default verbose output based on release branch
is_debug_build

# Initialize backup directories
upgrade_init_backup

# Initialize logging
upgrade_init_logging

# Set up console display and welcome message
upgrade_welcome_message_log >> $LOG
upgrade_welcome_message

# Back up existing configuration files and templates
upgrade_start_backup | tee -a $LOG

# Execute version-specific upgrade scripts
upgrade_start_routine | tee -a $LOG

# Upgrade File Manager and update configuration
upgrade_filemanager | tee -a $LOG
update_filemanager_configuration | tee -a $LOG

# Update Web domain templates
update_web_templates | tee -a $LOG

# Update Mail domain templates
update_mail_templates | tee -a $LOG

# Update DNS zone templastes
update_dns_templates | tee -a $LOG

# Upgrade phpMyAdmin if applicable
upgrade_phpmyadmin | tee -a $LOG

# Set new version number in hestia.conf
upgrade_set_version $new_version

# Perform account and domain rebuild to ensure configuration files are correct
upgrade_rebuild_users | tee -a $LOG

# Restart necessary services for changes to take full effect
upgrade_restart_services | tee -a $LOG

# Perform upgrade clean-up tasks
upgrade_perform_cleanup | tee -a $LOG

# Add upgrade notification to admin user's panel and display completion message
upgrade_complete_message_log >> $LOG
upgrade_complete_message

# If setting variable is true, send the log to admin account's email address.
upgrade_send_log_to_admin

exit 0
